# Root module — composes all infra for one environment.

# required_providers is generated by Terragrunt, not declared here.
terraform {
  required_version = ">= 1.15"
}

# Skipped when this environment borrows dev's VPC (e.g. qa).
module "network" {
  count = var.enable_network ? 1 : 0

  source = "./modules/network"

  environment          = var.environment
  vpc_cidr             = var.vpc_cidr
  az_count             = var.az_count
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  enable_vpc_endpoints = var.enable_vpc_endpoints
  tags                 = var.tags
}

locals {
  vpc_id             = var.enable_network ? module.network[0].vpc_id : var.dev_vpc_id
  vpc_cidr_effective = var.enable_network ? module.network[0].vpc_cidr : var.dev_vpc_cidr
  public_subnet_ids  = var.enable_network ? module.network[0].public_subnet_ids : var.dev_public_subnet_ids
  private_subnet_ids = var.enable_network ? module.network[0].private_subnet_ids : var.dev_private_subnet_ids

  # The one service with expose_publicly = true.
  public_service_name = [for k, v in var.services : k if v.expose_publicly][0]

  # Proxy endpoint when enabled, Aurora's own endpoint otherwise.
  db_host = var.enable_rds_proxy ? module.rds_proxy[0].endpoint : module.aurora.endpoint

  # Shared Aurora connection info, merged into thor/task-api only (service-specific values stay in terragrunt.hcl).
  services_with_shared_secrets = {
    for k, v in var.services : k => contains(["thor", "task-api"], k) ? merge(v, {
      secrets = merge(v.secrets, {
        DB_USERNAME = "${module.aurora.master_user_secret_arn}:username::"
        DB_PASSWORD = "${module.aurora.master_user_secret_arn}:password::"
      })
      environment_variables = merge(v.environment_variables, {
        DB_HOST = local.db_host
        DB_NAME = module.aurora.database_name
        DB_PORT = "5432"
      })
    }) : v
  }
}

# Always on — enable_compute gates resources inside the module instead.
module "ecs" {
  source = "./modules/ecs"

  environment               = var.environment
  enable_compute            = var.enable_compute
  vpc_id                    = local.vpc_id
  vpc_cidr                  = local.vpc_cidr_effective
  private_subnet_ids        = local.private_subnet_ids
  enable_container_insights = var.enable_container_insights

  services = local.services_with_shared_secrets

  aurora_cluster_arn = module.aurora.cluster_arn
  aurora_secret_arn  = module.aurora.master_user_secret_arn

  tags = var.tags
}

locals {
  # var.hosted_zones nests certificates under their zone for readability in
  # terragrunt.hcl — modules/route53 and modules/acm both stay flat and
  # generic, so this flattening happens here, once, at the boundary.

  # zones map for modules/route53: keyed by the real domain name (zone_name),
  # not hosted_zones' own logical keys.
  route53_zones = {
    for zone_key, zone in var.hosted_zones : zone.zone_name => {
      create_zone = zone.create_zone
      comment     = zone.comment
      tags        = zone.tags
    }
  }

  # Every certificate across every zone, flattened into one map. Keyed by
  # "<zone_key>/<cert_key>" so short, repeated cert names (e.g. "api" in two
  # different zones) never collide once flattened. zone_name rides along on
  # each entry so the zone_id lookup below knows which zone to resolve.
  route53_certificates_flat = merge([
    for zone_key, zone in var.hosted_zones : {
      for cert_key, cert in zone.certificates : "${zone_key}/${cert_key}" => merge(cert, {
        zone_name = zone.zone_name
      })
    }
  ]...)
}


module "route53" {
  count = var.enable_route53 ? 1 : 0

  source = "./modules/route53"

  zones = local.route53_zones
  tags  = var.tags
}

module "acm" {
  count = var.enable_route53 ? 1 : 0

  source = "./modules/acm"

  certificates = {
    for key, cert in local.route53_certificates_flat : key => {
      domain_name               = cert.domain_name
      subject_alternative_names = cert.subject_alternative_names
      zone_id                   = module.route53[0].zone_ids[cert.zone_name]
    }
  }

  tags = var.tags
}

locals {
  # "" until enable_route53 is on and frontend_certificate_key actually
  # points at an entry — keeps module.frontend's domain_name/etc. defaulted
  # to "" (its own "no custom domain" fallback) rather than erroring.
  frontend_route53 = var.enable_route53 && var.frontend_certificate_key != "" ? {
    domain_name     = local.route53_certificates_flat[var.frontend_certificate_key].domain_name
    certificate_arn = module.acm[0].certificate_arns[var.frontend_certificate_key]
    zone_id         = module.route53[0].zone_ids[local.route53_certificates_flat[var.frontend_certificate_key].zone_name]
  } : null

  # Same pattern as frontend_route53, for the API Gateway custom domain.
  apigw_route53 = var.enable_route53 && var.api_gateway_certificate_key != "" ? {
    domain_name     = local.route53_certificates_flat[var.api_gateway_certificate_key].domain_name
    certificate_arn = module.acm[0].certificate_arns[var.api_gateway_certificate_key]
    zone_id         = module.route53[0].zone_ids[local.route53_certificates_flat[var.api_gateway_certificate_key].zone_name]
  } : null
}

# Private S3 + CloudFront for the frontend SPA.
module "frontend" {
  count = var.enable_frontend ? 1 : 0

  source = "./modules/frontend"

  environment = var.environment
  price_class = var.frontend_price_class

  domain_name         = local.frontend_route53 != null ? local.frontend_route53.domain_name : ""
  acm_certificate_arn = local.frontend_route53 != null ? local.frontend_route53.certificate_arn : ""
  zone_id             = local.frontend_route53 != null ? local.frontend_route53.zone_id : ""

  tags = var.tags
}

# Needs the NLB listener, so gated with ecs's enable_compute.
module "api_gateway" {
  count = var.enable_compute ? 1 : 0

  source = "./modules/api_gateway"

  environment        = var.environment
  service_name       = local.public_service_name
  nlb_listener_arn   = module.ecs.nlb_listener_arns[local.public_service_name]
  vpc_id             = local.vpc_id
  private_subnet_ids = local.private_subnet_ids

  enable_authorizer               = var.enable_authorizer
  authorizer_lambda_invoke_arn    = var.enable_authorizer ? module.lambda[0].lambda_invoke_arn : ""
  authorizer_lambda_function_name = var.enable_authorizer ? module.lambda[0].lambda_function_name : ""

  domain_name         = local.apigw_route53 != null ? local.apigw_route53.domain_name : ""
  acm_certificate_arn = local.apigw_route53 != null ? local.apigw_route53.certificate_arn : ""
  zone_id             = local.apigw_route53 != null ? local.apigw_route53.zone_id : ""

  tags = var.tags
}

# Salt for Thor.Authorizer's PBKDF2 API-key hashing — value set out-of-band, not by Terraform.
module "secrets" {
  count = var.enable_authorizer ? 1 : 0

  source = "./modules/secrets"

  environment = var.environment
  tags        = var.tags
}

# Validates API keys against Aurora via RDS Data API — no VPC needed.
module "lambda" {
  count = var.enable_authorizer ? 1 : 0

  source = "./modules/lambda"

  environment          = var.environment
  aurora_cluster_arn   = module.aurora.cluster_arn
  aurora_secret_arn    = module.aurora.master_user_secret_arn
  aurora_database_name = module.aurora.database_name

  authorizer_salt_secret_arn = module.secrets[0].authorizer_salt_secret_arn

  runtime               = var.authorizer_lambda_runtime
  timeout               = var.authorizer_lambda_timeout
  memory_size           = var.authorizer_lambda_memory_size
  authorizer_source_dir = var.authorizer_source_dir

  tags = var.tags
}

# Aurora database.
module "aurora" {
  source = "./modules/aurora"

  environment        = var.environment
  vpc_id             = local.vpc_id
  vpc_cidr           = local.vpc_cidr_effective
  private_subnet_ids = local.private_subnet_ids
  # Only the proxy reaches Aurora directly — thor/task-api go through it, not around it.
  allowed_security_group_ids = var.enable_rds_proxy ? {
    rds-proxy = module.rds_proxy[0].rds_proxy_security_group_id
  } : {}

  database_name         = var.aurora_database_name
  master_username       = var.aurora_master_username
  engine_version        = var.aurora_engine_version
  min_capacity          = var.aurora_min_capacity
  max_capacity          = var.aurora_max_capacity
  backup_retention_days = var.aurora_backup_retention_days
  deletion_protection   = var.aurora_deletion_protection
  skip_final_snapshot   = var.aurora_skip_final_snapshot

  tags = var.tags
}

# Connection pooling in front of Aurora — thor/task-api connect here instead of Aurora's own endpoint.
module "rds_proxy" {
  count = var.enable_rds_proxy ? 1 : 0

  source = "./modules/rds_proxy"

  environment        = var.environment
  vpc_id             = local.vpc_id
  vpc_cidr           = local.vpc_cidr_effective
  private_subnet_ids = local.private_subnet_ids

  aurora_cluster_identifier = module.aurora.cluster_identifier
  aurora_secret_arn         = module.aurora.master_user_secret_arn

  allowed_security_group_ids = var.enable_compute ? {
    thor     = module.ecs.service_security_group_ids["thor"]
    task-api = module.ecs.service_security_group_ids["task-api"]
  } : {}

  tags = var.tags
}

# RDS Proxy and Neptune: future work.
