#!/usr/bin/env bash
# Creates (or updates) the GitHub Actions deploy IAM role for one
# environment, assumed via OIDC — no long-lived AWS credentials in GitHub.
# One role per environment, shared by both thor-demo-backend (ECS deploys)
# and thor-demo-frontend (S3/CloudFront deploys) — trusted by both repos'
# matching GitHub Environment, granted both apps' permissions.
#
# Most resource ARNs are constructed from this project's fixed naming
# convention (thor-<env>-<service>-execution/-task, thor-<env> cluster,
# <service>-<env> ECR repo, thor-frontend-<env>-<account> bucket), not read
# from `terragrunt output` — the convention is controlled on both the
# Terraform and script side, so there's nothing to look up for those. This
# also means the role can be created before `terragrunt apply` has ever run:
# IAM doesn't validate that a policy's Resource ARN actually exists yet, only
# that it's well-formed.
#
# CloudFront's CreateInvalidation is scoped to the account (distribution/*),
# not one specific distribution ARN — the distribution ID is generated by
# AWS, not something this script can predict from a naming convention alone.
#
# Prerequisite: create-github-oidc-provider.sh already run in this account.
#
# Usage: ./create-deploy-role.sh <environment> <github_org> [aws_profile] [region] [upstream_account_id]
#   environment         dev, qa, or prod.
#   github_org          the GitHub org/user that owns both repos (no sensible default).
#   region              defaults to us-east-1 (matches infra/root.hcl's account_map).
#   upstream_account_id account this role needs read access to for pull-and-retag
#     promotion. Not used for dev (no upstream). For qa, defaults to this same
#     account (dev and qa share one, per infra/root.hcl) if omitted. For prod,
#     there's no safe default — qa's account ID must be passed explicitly.
#     Same-account (dev -> qa) works via IAM policy alone; cross-account
#     (qa -> prod) additionally needs the upstream environment's ecs module
#     cross_account_pull_principal_arns set to this role's ARN once it's
#     created — see ecs/ecr.tf.

set -euo pipefail

ENVIRONMENT="${1:?Usage: create-deploy-role.sh <environment> <github_org> [aws_profile] [region] [upstream_account_id]}"
GITHUB_ORG="${2:?GitHub org/user is required}"
GITHUB_REPO="${GITHUB_REPO:-thor-demo-backend}"
FRONTEND_GITHUB_REPO="${FRONTEND_GITHUB_REPO:-thor-demo-frontend}"
export AWS_PROFILE="${3:-${AWS_PROFILE:-default}}"
REGION="${4:-us-east-1}"
UPSTREAM_ACCOUNT_ID="${5:-}"

SERVICES=(thor task-api intelligence-engine)

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
ROLE_NAME="deploy-${ENVIRONMENT}"
OIDC_PROVIDER_ARN="arn:aws:iam::${ACCOUNT_ID}:oidc-provider/token.actions.githubusercontent.com"

echo "Using AWS profile '${AWS_PROFILE}' -> account ${ACCOUNT_ID}, environment '${ENVIRONMENT}', region '${REGION}'."

if ! aws iam get-open-id-connect-provider --open-id-connect-provider-arn "${OIDC_PROVIDER_ARN}" >/dev/null 2>&1; then
  echo "No GitHub OIDC provider found in this account (${OIDC_PROVIDER_ARN}). Run create-github-oidc-provider.sh first."
  exit 1
fi

json_arn_list() {
  local template="$1"
  printf '%s\n' "${SERVICES[@]}" | jq -R --arg env "${ENVIRONMENT}" --arg account "${ACCOUNT_ID}" --arg region "${REGION}" "${template}" | jq -s .
}

ECR_REPO_ARNS_JSON="$(json_arn_list '"arn:aws:ecr:\($region):\($account):repository/\(.)-\($env)"')"
SERVICE_ARNS_JSON="$(json_arn_list '"arn:aws:ecs:\($region):\($account):service/thor-\($env)/\(.)"')"
EXEC_ROLE_ARNS_JSON="$(json_arn_list '"arn:aws:iam::\($account):role/thor-\($env)-\(.)-execution"')"
TASK_ROLE_ARNS_JSON="$(json_arn_list '"arn:aws:iam::\($account):role/thor-\($env)-\(.)-task"')"
PASS_ROLE_ARNS_JSON="$(jq -n --argjson a "${EXEC_ROLE_ARNS_JSON}" --argjson b "${TASK_ROLE_ARNS_JSON}" '$a + $b')"

# Bucket name follows the same convention as the frontend Terraform module's
# local.bucket_name — safe to construct even before that module has run.
FRONTEND_BUCKET_ARN="arn:aws:s3:::thor-frontend-${ENVIRONMENT}-${ACCOUNT_ID}"

UPSTREAM_ECR_ARNS_JSON="[]"
if [[ "${ENVIRONMENT}" == "qa" ]]; then
  UPSTREAM_ACCOUNT_ID="${UPSTREAM_ACCOUNT_ID:-${ACCOUNT_ID}}"
  UPSTREAM_ECR_ARNS_JSON="$(printf '%s\n' "${SERVICES[@]}" | jq -R --arg account "${UPSTREAM_ACCOUNT_ID}" --arg region "${REGION}" '"arn:aws:ecr:\($region):\($account):repository/\(.)-dev"' | jq -s .)"
elif [[ "${ENVIRONMENT}" == "prod" ]]; then
  [[ -n "${UPSTREAM_ACCOUNT_ID}" ]] || { echo "prod needs qa's account ID as the 5th argument (no safe default — it's a different account)."; exit 1; }
  UPSTREAM_ECR_ARNS_JSON="$(printf '%s\n' "${SERVICES[@]}" | jq -R --arg account "${UPSTREAM_ACCOUNT_ID}" --arg region "${REGION}" '"arn:aws:ecr:\($region):\($account):repository/\(.)-qa"' | jq -s .)"
fi

# qa additionally trusts qa-candidate — backend-qa.yml's `deploy` job (the
# candidate build+test step) runs under that unprotected GitHub Environment,
# so the candidate can deploy and be tested automatically before there's
# anything to approve; `promote` still runs under plain `qa`, which is where
# required reviewers actually get configured. One role, two trusted
# environment names for qa; dev/prod stay single-element arrays.
#
# The frontend repo's matching environment (dev/qa/prod, same names as this
# script's ENVIRONMENT) is trusted too, in every environment — thor-demo-frontend
# has no candidate/promote split like the backend's qa does.
SUB_VALUES=(
  "repo:${GITHUB_ORG}/${GITHUB_REPO}:environment:${ENVIRONMENT}"
  "repo:${GITHUB_ORG}/${FRONTEND_GITHUB_REPO}:environment:${ENVIRONMENT}"
)
if [[ "${ENVIRONMENT}" == "qa" ]]; then
  SUB_VALUES+=("repo:${GITHUB_ORG}/${GITHUB_REPO}:environment:qa-candidate")
fi
SUB_JSON="$(printf '%s\n' "${SUB_VALUES[@]}" | jq -R . | jq -s .)"

# Scoped to this GitHub Environment(s) (dev/qa/prod, plus qa-candidate for
# qa) — deployment_strategy_plan.md §6.2 already calls for 3 GitHub
# Environments named to match. StringEquals accepts an array of values, so
# this works identically whether SUB_JSON has one entry or two.
TRUST_POLICY="$(jq -n \
  --arg oidc_arn "${OIDC_PROVIDER_ARN}" \
  --argjson subs "${SUB_JSON}" \
  '{
    Version: "2012-10-17",
    Statement: [{
      Effect: "Allow",
      Principal: { Federated: $oidc_arn },
      Action: "sts:AssumeRoleWithWebIdentity",
      Condition: {
        StringEquals: {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
          "token.actions.githubusercontent.com:sub": $subs
        }
      }
    }]
  }'
)"

# ECS RegisterTaskDefinition/DescribeTaskDefinition don't support resource-level scoping (AWS requires "*"); everything else is scoped to this environment's actual resources, built from the fixed naming convention.
PERMISSIONS_POLICY="$(jq -n \
  --argjson ecr_repos "${ECR_REPO_ARNS_JSON}" \
  --argjson upstream_ecr_repos "${UPSTREAM_ECR_ARNS_JSON}" \
  --argjson service_arns "${SERVICE_ARNS_JSON}" \
  --argjson pass_role_arns "${PASS_ROLE_ARNS_JSON}" \
  --arg frontend_bucket_arn "${FRONTEND_BUCKET_ARN}" \
  --arg frontend_distribution_arn "arn:aws:cloudfront::${ACCOUNT_ID}:distribution/*" \
  '{
    Version: "2012-10-17",
    Statement: (
      [
        { Sid: "EcrAuth", Effect: "Allow", Action: ["ecr:GetAuthorizationToken"], Resource: "*" },
        { Sid: "EcrPushOwn", Effect: "Allow", Action: ["ecr:BatchCheckLayerAvailability","ecr:PutImage","ecr:InitiateLayerUpload","ecr:UploadLayerPart","ecr:CompleteLayerUpload","ecr:BatchGetImage","ecr:GetDownloadUrlForLayer"], Resource: $ecr_repos },
        { Sid: "EcsRegisterTaskDef", Effect: "Allow", Action: ["ecs:RegisterTaskDefinition","ecs:DescribeTaskDefinition"], Resource: "*" },
        { Sid: "EcsUpdateService", Effect: "Allow", Action: ["ecs:UpdateService","ecs:DescribeServices"], Resource: $service_arns },
        { Sid: "PassEcsRoles", Effect: "Allow", Action: ["iam:PassRole"], Resource: $pass_role_arns, Condition: { StringEquals: { "iam:PassedToService": "ecs-tasks.amazonaws.com" } } },
        { Sid: "FrontendListBucket", Effect: "Allow", Action: ["s3:ListBucket"], Resource: [$frontend_bucket_arn] },
        { Sid: "FrontendSyncObjects", Effect: "Allow", Action: ["s3:GetObject","s3:PutObject","s3:DeleteObject"], Resource: ["\($frontend_bucket_arn)/*"] },
        { Sid: "FrontendInvalidateCache", Effect: "Allow", Action: ["cloudfront:CreateInvalidation"], Resource: [$frontend_distribution_arn] }
      ]
      # DescribeImages: backend-qa.yml/backend-prod.yml's "Resolve tag to promote" step queries the upstream repo directly for its latest pushed (non-candidate) image, rather than trusting any particular git event's SHA.
      + (if ($upstream_ecr_repos | length) > 0 then [{ Sid: "EcrPullUpstream", Effect: "Allow", Action: ["ecr:BatchGetImage","ecr:GetDownloadUrlForLayer","ecr:BatchCheckLayerAvailability","ecr:DescribeImages"], Resource: $upstream_ecr_repos }] else [] end)
    )
  }'
)"

if aws iam get-role --role-name "${ROLE_NAME}" >/dev/null 2>&1; then
  echo "Role ${ROLE_NAME} already exists — updating trust policy and permissions."
  aws iam update-assume-role-policy --role-name "${ROLE_NAME}" --policy-document "${TRUST_POLICY}"
else
  read -rp "Create IAM role ${ROLE_NAME} in account ${ACCOUNT_ID}? [y/N] " CONFIRM
  [[ "${CONFIRM}" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
  aws iam create-role --role-name "${ROLE_NAME}" --assume-role-policy-document "${TRUST_POLICY}"
fi

aws iam put-role-policy --role-name "${ROLE_NAME}" --policy-name "deploy-permissions" --policy-document "${PERMISSIONS_POLICY}"

ROLE_ARN="$(aws iam get-role --role-name "${ROLE_NAME}" --query 'Role.Arn' --output text)"
echo "Role ready: ${ROLE_ARN}"
echo "This role is shared by both ${GITHUB_REPO} and ${FRONTEND_GITHUB_REPO} — set it as the AWS_ROLE_ARN variable on the matching GitHub Environment(s) in BOTH repos."
if [[ "${ENVIRONMENT}" == "qa" ]]; then
  echo "For ${GITHUB_REPO}: add it to BOTH the 'qa-candidate' and 'qa' GitHub Environments."
  echo "For ${FRONTEND_GITHUB_REPO}: add it to the 'qa' GitHub Environment."
else
  echo "Add it to the '${ENVIRONMENT}' GitHub Environment in each repo."
fi
